/** Generated from schema.json; defend wire compatibility (ADR 0006). Do not edit. */
export type Contents = { "text"?: boolean | { "maxCharacters"?: number; }; "highlights"?: boolean | { "query"?: string; "maxCharacters"?: number; }; "summary"?: boolean | { "query"?: string; "schema"?: { [key: string]: unknown; }; }; "maxAgeHours"?: number; "livecrawlTimeout"?: number; };
export type Search = { "query": string; "type"?: "auto" | "fast" | "instant" | "deep-lite" | "deep" | "deep-reasoning"; "numResults"?: number; "includeDomains"?: (string)[]; "excludeDomains"?: (string)[]; "category"?: "company" | "publication" | "news" | "personal site" | "financial report" | "people"; "startPublishedDate"?: string; "endPublishedDate"?: string; "contents"?: Contents; "userLocation"?: string; "outputSchema"?: { [key: string]: unknown; }; "systemPrompt"?: string; [key: string]: unknown; };
export type Fetch = { "urls": (string)[]; "text"?: boolean | { "maxCharacters"?: number; }; "highlights"?: boolean | { "query"?: string; "maxCharacters"?: number; }; "summary"?: boolean | { "query"?: string; "schema"?: { [key: string]: unknown; }; }; "maxAgeHours"?: number; "livecrawlTimeout"?: number; [key: string]: unknown; };
export type Answer = { "query": string; "text"?: boolean; "systemPrompt"?: string; "outputSchema"?: { [key: string]: unknown; }; "userLocation"?: string; [key: string]: unknown; };
export type AgentStart = { "query": string; "effort"?: "minimal" | "low" | "medium" | "high" | "xhigh" | "auto" | "max"; "maxCostDollars"?: number; "outputSchema"?: { [key: string]: unknown; }; "systemPrompt"?: string; "previousRunId"?: string; "input"?: { "data"?: ({ [key: string]: unknown; })[]; "exclusion"?: ({ [key: string]: unknown; })[]; }; [key: string]: unknown; };
export type AgentId = { "id": string; [key: string]: unknown; };
export type Result = { "id"?: string; "url": string; "title"?: string | null; "publishedDate"?: string | null; "author"?: string | null; "text"?: string | null; "highlights"?: (string)[]; "summary"?: string | { [key: string]: unknown; } | null; [key: string]: unknown; };
export type Cost = { "total"?: number; [key: string]: unknown; };
export type SearchResponse = { "requestId"?: string; "results": (Result)[]; "output"?: { [key: string]: unknown; } | null; "costDollars"?: Cost; [key: string]: unknown; };
export type ContentsResponse = { "requestId"?: string; "results": (Result)[]; "statuses"?: ({ [key: string]: unknown; })[]; "costDollars"?: Cost; [key: string]: unknown; };
export type AnswerResponse = { "requestId"?: string; "answer": string | { [key: string]: unknown; }; "citations"?: (Result)[]; "costDollars"?: Cost; [key: string]: unknown; };
export type AgentResponse = { "id": string; "status": "queued" | "running" | "completed" | "failed" | "cancelled"; "stopReason"?: string | null; "output"?: { [key: string]: unknown; } | null; "usage"?: { [key: string]: unknown; } | null; "costDollars"?: { [key: string]: unknown; } | null; [key: string]: unknown; };
export type Settings = { "deadlineMs": number; "responseBytes": number; "requestBytes": number; "concurrency": number; "agentMaxCostDollars": number; "runLimit": number; "searchPrice": number; "deepPrice": number; "reasoningPrice": number; "resultPrice": number; "contentPrice": number; "answerPrice": number; };
export type Owners = { "version": 1; "runs": ({ "id": string; "person": string; "effort": string; })[]; };
export type Contract = Owners;
