// JSON file storage for the plan and for recorded questions, one file per conversation
// so sessions never see each other's state. Kept dependency-free: plain fs + JSON.
import { readFile, writeFile, rename, unlink, mkdir } from "node:fs/promises";
import { dirname, basename, resolve } from "node:path";

async function atomicWriteJSON(absolute, obj) {
  await mkdir(dirname(absolute), { recursive: true });
  const tmp = resolve(dirname(absolute), `.${basename(absolute)}.tmp-${process.pid}-${Date.now()}`);
  await writeFile(tmp, JSON.stringify(obj, null, 2));
  await rename(tmp, absolute).catch(async (e) => {
    await unlink(tmp).catch(() => {});
    throw e;
  });
}

async function readJSON(absolute, fallback) {
  try {
    return JSON.parse(await readFile(absolute, "utf8"));
  } catch (e) {
    if (e.code === "ENOENT") return fallback;
    throw e;
  }
}

// Sanitize a session id for use as a filename component: keep it simple and predictable,
// since session ids are generated by the kernel, not by the model.
function safeName(sessionId) {
  return String(sessionId).replace(/[^a-zA-Z0-9._-]/g, "_");
}

export function planPath(home, sessionId) {
  return resolve(home, "plans", `${safeName(sessionId)}.json`);
}

export function questionsPath(home, sessionId) {
  return resolve(home, "questions", `${safeName(sessionId)}.json`);
}

export async function loadPlan(home, sessionId) {
  return readJSON(planPath(home, sessionId), { items: [], nextId: 1 });
}

export async function savePlan(home, sessionId, plan) {
  await atomicWriteJSON(planPath(home, sessionId), plan);
}

export async function loadQuestions(home, sessionId) {
  return readJSON(questionsPath(home, sessionId), { entries: [] });
}

export async function saveQuestions(home, sessionId, data) {
  await atomicWriteJSON(questionsPath(home, sessionId), data);
}
